INSERT INTO KMR_Pais (nombre,continente)
    VALUES
	('Afganistan','Asia'),
	('Islas Gland','Europa'),
	('Albania','Europa'),
	('Alemania','Europa'),
	('Andorra','Europa'),
	('Angola','Africa'),
	('Anguilla','America'),
	('Antigua y Barbuda','America'),
	('Arabia Saudi','Asia'),
	('Argelia','Africa'),
	('Argentina','America'),
	('Armenia','Europa'),
	('Aruba', 'America'),
	('Australia','Oceania'),
	('Austria','Europa'),
	('Azerbaiyán','Asia'),
	('Bahamas','America'),
	('Bahrein','Asia'),
	('Bangladesh','Asia'),
	('Barbados','America'),
	('Bielorrusia','Europa'),
	('Bélgica','Europa'),
	('Belice','America'),
	('Benin','Africa'),
	('Bermudas','America'),
	('Bhutan','Asia'),
	('Bolivia','America'),
	('Bosnia y Herzegovina','Europa'),
	('Botsuana','Africa'),
	('Isla Bouvet','Antartida'),
	('Brasil','America'),
	('Brunéi','Asia'),
	('Bulgaria','Europa'),
	('Burkina Faso','Africa'),
	('Burundi','Asia'),
	('Cabo Verde','Africa'),
	('Islas Caiman','America'),
	('Camboya','Asia'),
	('Camerun','Africa'),
	('Canada','America'),
	('Republica Centroafricana','Africa'),
	('Chad','Africa'),
	('Chequia','Europa'),
	('Chile','America'),
	('China','Asia'),
	('Chipre','Europa'),
	('Colombia', 'America'),
	('Comoras','Africa'),
	('Congo','Africa'),
	('Islas Cook','Oceania'),
	('Corea del Norte','Asia'),
	('Corea del Sur','Asia'),
	('Costa de Marfil','Africa'),
	('Costa Rica','America'),
	('Croacia','Europa'),
	('Cuba','America'),
	('Dinamarca','Europa'),
	('Dominica','America'),
	('Republica Dominicana','America'),
	('Ecuador','America'),
	('Egipto','Africa'),
	('El Salvador','America'),
	('Emiratos Arabes Unidos','Asia'),
	('Eritrea','Africa'),
	('Eslovaquia','Europa'),
	('Eslovenia','Europa'),
	('España','Europa'),
	('Estados Unidos','America'),
	('Estonia','Europa'),
	('Etiopía','Africa'),
	('Islas Feroe','Europa'),
	('Filipinas','Asia'),
	('Finlandia','Europa'),
	('Fiyi','Oceania'),
	('Francia','Europa'),
	('Gabon','Africa'),
	('Gambia','Africa'),
	('Georgia','Europa'),
	('Ghana','Africa'),
	('Granada','America'),
	('Grecia', 'Europa'),
	('Groenlandia','America'),
	('Guatemala','America'),
	('Guinea','Africa'),
	('Guyana','America'),
	('Haití','America'),
	('Honduras','America'),
	('Hungría','Europa'),
	('India','Asia'),
	('Indonesia','Asia'),
	('Irán','Asia'),
	('Irak','Asia'),
	('Irlanda','Europa'),
	('Islandia','Europa'),
	('Israel','Asia'),
	('Italia','Europa'),
	('Jamaica','America'),
	('Japón','Asia'),
	('Jordania','Asia'),
	('Kazajstán','Asia'),
	('Kenia','Africa'),
	('Kirguistán','Asia'),
	('Kiribati','Oceania'),
	('Kuwait','Asia'),
	('Laos','Asia'),
	('Lesotho','Africa'),
	('Letonia','Europa'),
	('Líbano','Asia'),
	('Liberia','Africa'),
	('Libia','Africa'),
	('Liechtenstein','Europa'),
	('Lituania','Europa'),
	('Luxemburgo','Europa'),
	('Madagascar','Africa'),
	('Malasia', 'Asia'),
	('Malawi','Africa'),
	('Maldivas','Asia'),
	('Malí','Africa'),
	('Malta','Europa'),
	('Islas Malvinas','America'),
	('Islas Marianas del Norte','Oceania'),
	('Marruecos','Africa'),
	('Islas Marshall','Oceania'),
	('Mauricio','Africa'),
	('Mauritania','Africa'),
	('México','America'),
	('Micronesia','Oceania'),
	('Moldavia','Europa'),
	('Mónaco','Europa'),
	('Mongolia','Asia'),
	('Mozambique','Africa'),
	('Birmania','Africa'),
	('Namibia','Africa'),
	('Nauru','Oceania'),
	('Nepal','Asia'),
	('Nicaragua','Asia'),
	('Níger','Africa'),
	('Nigeria','Africa'),
	('Niue','Oceania'),
	('Noruega','Europa'),
	('Nueva Zelanda','Oceania'),
	('Omán','Asia'),
	('Países Bajos','Europa'),
	('Pakistán','Asia'),
	('Palau','Oceania'),
	('Palestina','Asia'),
	('Panamá','America'),
	('Papúa Nueva Guinea','Oceania'),
	('Paraguay','America'),
	('Perú','America'),
	('Polonia','Europa'),
	('Portugal','Europa'),
	('Puerto Rico','America'),
	('Qatar','Asia'),
	('Reino Unido','Europa'),
	('Reunión','Africa'),
	('Ruanda','Africa'),
	('Rumania','Europa'),
	('Rusia','Europa'),
	('Islas Salomón','Oceania'),
	('Samoa','Oceania'),
	('San Cristóbal y Nevis','America'),
	('San Marino','Europa'),
	('San Vicente y las Granadinas','America'),
	('Santa Lucía','America'),
	('Santo Tomé y Príncipe','Africa'),
	('Senegal','Africa'),
	('Seychelles','Africa'),
	('Sierra Leona','Africa'),
	('Singapur','Asia'),
	('Siria','Asia'),
	('Somalia','Africa'),
	('Sri Lanka','Asia'),
	('Suazilandia','Africa'),
	('Sudáfrica','Africa'),
	('Sudán','Africa'),
	('Suecia','Europa'),
	('Suiza','Europa'),
	('Surinam','America'),
	('Tailandia','Asia'),
	('Taiwán','Asia'),
	('Tanzania','Africa'),
	('Tayikistán','Asia'),
	('Timor Oriental','Asia'),
	('Togo','Africa'),
	('Tonga','Oceania'),
	('Trinidad y Tobago','America'),
	('Túnez','Africa'),
	('Turkmenistán','Asia'),
	('Turquía','Asia'),
	('Tuvalu','Oceania'),
	('Ucrania','Europa'),
	('Uganda','Africa'),
	('Uruguay','America'),
	('Uzbekistán','Asia'),
	('Vanuatu','Oceania'),
	('Venezuela','America'),
	('Vietnam','Asia'),
	('Yemen','Asia'),
	('Yibuti','Africa'),
	('Zambia','Africa'),
	('Zimbabue','Africa');

INSERT INTO KMR_Asociacion_Nacional
    VALUES 
	(1,'Asociación Chilena de Sabores y Fragancias Asociación','Region Metropolitana',44),
	(2,'Cosmetic,Toiletry and Frangance Association of Singapore','Central Business District, Singapore',170),
	(3,'South African Association of the Flavour & Fragrance Industry','Johannesburg, Gauteng',175);

INSERT INTO KMR_Empresa_Productora 
    VALUES
	(1,'IFF','https://www.iff.com','+1 (212) 765-5500',NULL),
	(2,'Firmenich','https://www.firmenich.com','https://www.firmenich.com/en_INT/contact.html',NULL),
	(3,'Aromex','http://www.aromex.cl','22 443 87 85',1),
	(4,'Sephora Asia Pte Ltd','https://www.sephora.sg','https://www.sephora.sg/contact-us',2),
	(5,'fourchem','http://www.fourchem.co.za','+27 (0)21 709 0517',3);
