INSERT INTO KMR_Pais (nombre,continente)
    VALUES
	('Afganistan','Asia'),
	('Islas Gland','Europa'),
	('Albania','Europa'),
	('Alemania','Europa'),
	('Andorra','Europa'),
	('Angola','Africa'),
	('Anguilla','America'),
	('Antigua y Barbuda','America'),
	('Arabia Saudi','Asia'),
	('Argelia','Africa'),
	('Argentina','America'),
	('Armenia','Europa'),
	('Aruba', 'America'),
	('Australia','Oceania'),
	('Austria','Europa'),
	('Azerbaiyán','Asia'),
	('Bahamas','America'),
	('Bahrein','Asia'),
	('Bangladesh','Asia'),
	('Barbados','America'),
	('Bielorrusia','Europa'),
	('Bélgica','Europa'),
	('Belice','America'),
	('Benin','Africa'),
	('Bermudas','America'),
	('Bhutan','Asia'),
	('Bolivia','America'),
	('Bosnia y Herzegovina','Europa'),
	('Botsuana','Africa'),
	('Isla Bouvet','Antartida'),
	('Brasil','America'),
	('Brunéi','Asia'),
	('Bulgaria','Europa'),
	('Burkina Faso','Africa'),
	('Burundi','Asia'),
	('Cabo Verde','Africa'),
	('Islas Caiman','America'),
	('Camboya','Asia'),
	('Camerun','Africa'),
	('Canada','America'),
	('Republica Centroafricana','Africa'),
	('Chad','Africa'),
	('Chequia','Europa'),
	('Chile','America'),
	('China','Asia'),
	('Chipre','Europa'),
	('Colombia', 'America'),
	('Comoras','Africa'),
	('Congo','Africa'),
	('Islas Cook','Oceania'),
	('Corea del Norte','Asia'),
	('Corea del Sur','Asia'),
	('Costa de Marfil','Africa'),
	('Costa Rica','America'),
	('Croacia','Europa'),
	('Cuba','America'),
	('Dinamarca','Europa'),
	('Dominica','America'),
	('Republica Dominicana','America'),
	('Ecuador','America'),
	('Egipto','Africa'),
	('El Salvador','America'),
	('Emiratos Arabes Unidos','Asia'),
	('Eritrea','Africa'),
	('Eslovaquia','Europa'),
	('Eslovenia','Europa'),
	('España','Europa'),
	('Estados Unidos','America'),
	('Estonia','Europa'),
	('Etiopía','Africa'),
	('Islas Feroe','Europa'),
	('Filipinas','Asia'),
	('Finlandia','Europa'),
	('Fiyi','Oceania'),
	('Francia','Europa'),
	('Gabon','Africa'),
	('Gambia','Africa'),
	('Georgia','Europa'),
	('Ghana','Africa'),
	('Granada','America'),
	('Grecia', 'Europa'),
	('Groenlandia','America'),
	('Guatemala','America'),
	('Guinea','Africa'),
	('Guyana','America'),
	('Haití','America'),
	('Honduras','America'),
	('Hungría','Europa'),
	('India','Asia'),
	('Indonesia','Asia'),
	('Irán','Asia'),
	('Irak','Asia'),
	('Irlanda','Europa'),
	('Islandia','Europa'),
	('Israel','Asia'),
	('Italia','Europa'),
	('Jamaica','America'),
	('Japón','Asia'),
	('Jordania','Asia'),
	('Kazajstán','Asia'),
	('Kenia','Africa'),
	('Kirguistán','Asia'),
	('Kiribati','Oceania'),
	('Kuwait','Asia'),
	('Laos','Asia'),
	('Lesotho','Africa'),
	('Letonia','Europa'),
	('Líbano','Asia'),
	('Liberia','Africa'),
	('Libia','Africa'),
	('Liechtenstein','Europa'),
	('Lituania','Europa'),
	('Luxemburgo','Europa'),
	('Madagascar','Africa'),
	('Malasia', 'Asia'),
	('Malawi','Africa'),
	('Maldivas','Asia'),
	('Malí','Africa'),
	('Malta','Europa'),
	('Islas Malvinas','America'),
	('Islas Marianas del Norte','Oceania'),
	('Marruecos','Africa'),
	('Islas Marshall','Oceania'),
	('Mauricio','Africa'),
	('Mauritania','Africa'),
	('México','America'),
	('Micronesia','Oceania'),
	('Moldavia','Europa'),
	('Mónaco','Europa'),
	('Mongolia','Asia'),
	('Mozambique','Africa'),
	('Birmania','Africa'),
	('Namibia','Africa'),
	('Nauru','Oceania'),
	('Nepal','Asia'),
	('Nicaragua','Asia'),
	('Níger','Africa'),
	('Nigeria','Africa'),
	('Niue','Oceania'),
	('Noruega','Europa'),
	('Nueva Zelanda','Oceania'),
	('Omán','Asia'),
	('Países Bajos','Europa'),
	('Pakistán','Asia'),
	('Palau','Oceania'),
	('Palestina','Asia'),
	('Panamá','America'),
	('Papúa Nueva Guinea','Oceania'),
	('Paraguay','America'),
	('Perú','America'),
	('Polonia','Europa'),
	('Portugal','Europa'),
	('Puerto Rico','America'),
	('Qatar','Asia'),
	('Reino Unido','Europa'),
	('Reunión','Africa'),
	('Ruanda','Africa'),
	('Rumania','Europa'),
	('Rusia','Europa'),
	('Islas Salomón','Oceania'),
	('Samoa','Oceania'),
	('San Cristóbal y Nevis','America'),
	('San Marino','Europa'),
	('San Vicente y las Granadinas','America'),
	('Santa Lucía','America'),
	('Santo Tomé y Príncipe','Africa'),
	('Senegal','Africa'),
	('Seychelles','Africa'),
	('Sierra Leona','Africa'),
	('Singapur','Asia'),
	('Siria','Asia'),
	('Somalia','Africa'),
	('Sri Lanka','Asia'),
	('Suazilandia','Africa'),
	('Sudáfrica','Africa'),
	('Sudán','Africa'),
	('Suecia','Europa'),
	('Suiza','Europa'),
	('Surinam','America'),
	('Tailandia','Asia'),
	('Taiwán','Asia'),
	('Tanzania','Africa'),
	('Tayikistán','Asia'),
	('Timor Oriental','Asia'),
	('Togo','Africa'),
	('Tonga','Oceania'),
	('Trinidad y Tobago','America'),
	('Túnez','Africa'),
	('Turkmenistán','Asia'),
	('Turquía','Asia'),
	('Tuvalu','Oceania'),
	('Ucrania','Europa'),
	('Uganda','Africa'),
	('Uruguay','America'),
	('Uzbekistán','Asia'),
	('Vanuatu','Oceania'),
	('Venezuela','America'),
	('Vietnam','Asia'),
	('Yemen','Asia'),
	('Yibuti','Africa'),
	('Zambia','Africa'),
	('Zimbabue','Africa');

INSERT INTO KMR_Asociacion_Nacional
    VALUES 
	(1,'Asociación Chilena de Sabores y Fragancias Asociación','Region Metropolitana',44),
	(2,'Cosmetic,Toiletry and Frangance Association of Singapore','Central Business District, Singapore',170),
	(3,'South African Association of the Flavour & Fragrance Industry','Johannesburg, Gauteng',175),
	(4,'Fragance Creator''s Association', 'Centro Rosslyn', 68),
	(5, 'Swiss Flavour and Fragrance Industry Association', 'Geneva', 178);
	
INSERT INTO KMR_Empresa_Productora 
    VALUES
	(1,'IFF','https://www.iff.com','+1 (212) 765-5500',NULL),
	(2,'Firmenich','https://www.firmenich.com','https://www.firmenich.com/en_INT/contact.html',NULL),
	(3,'Aromex','http://www.aromex.cl','22 443 87 85',1),
	(4,'Sephora Asia Pte Ltd','https://www.sephora.sg','https://www.sephora.sg/contact-us',2),
	(5,'fourchem','http://www.fourchem.co.za','+27 (0)21 709 0517',3);

INSERT INTO KMR_Perfume
    VALUES 
	(1,'Geo Donna','F','M','AD',1),
	(2,'Flags Donna','F','M','JO',1),
	(3,'Geo Uomo','M','H','AT',1),
	(4,'L Eau d Issey Pour Femme','F','M','JO',2),
	(5,'L Eau d Issey Pour Homme','F','H','AD',2),
	(6,'Flower by Kenzo','F','M','JO',2),
	(7,'Kenzo Amour','F','M','JO',3),
	(8,'Hugo Dark Blue','F','H','AD',3),
	(9,'Miracle de Lancome','F','M','JO',3),
	(10,'Tiffany & Love For Her ','F','M','AT',4),
	(11,'Sauvage Eau de Parfum','F','H','AD',4),
	(12,'Bloom Eau De Parfum','M','M','AT',4),
	(13,'Love Secret','F','M','AT',5),
	(14,'Secret Charm','M','M','AT',5),
	(15,'Vitality','F','M','AD',5);
	
INSERT INTO KMR_Empresa_Proveedora
	(nombre, pag_web, inf_contacto, id_asoc_nacional)
	VALUES
	('Keva', 'https://www.keva.co.in/content/ingredients', '+91 22 2206 9609', NULL),
	('essence', 'https://essencia.ch/oele.php?pageID=89&language=E', '+41 52 245 05 60', 5),
	('Privi Organics India Limited', 'http://www.privi.com/', '+91 22 33043500', NULL),
	('Perfumer''s Apprentice', 'https://shop.perfumersapprentice.com', '1(877)627-7401', 4);

INSERT INTO KMR_Condiciones_Pago
	(id_emp_prov, tipo, cuotas)
	VALUES
	(1, 'AP', 3),
	(2, 'AP', 2),
	(3, 'AP', 1),
	(4, 'AP', 2),
	(1, 'C', NULL),
	(2, 'C', NULL),
	(3, 'C', NULL),
	(4, 'C', NULL);

INSERT INTO KMR_Envio_Pais
	(id_emp_prov, id_pais, dias_entrega, tipo_transporte, costo)
    VALUES
	(4, 14, 4, 'A', 6.35),
	(4, 44, 4, 'A', 6.35),
	(4, 45, 4, 'A', 6.35),
	(2,  4, 4, 'A', 2.17),
	(2, 14, 4, 'A', 2.17),
	(2, 91, 4, 'A', 2.17),
	(1, 89, 2, 'A', NULL),
	(3, 89, 2, 'A', NULL),
	(3, 68, 5, 'B', 5.00),
	(3, 126, 5, 'B', 5.00);


INSERT INTO KMR_IFRA_Ingrediente
	VALUES
	(131766739, 1, 'Un liquido amarillo pálido claro.', 'Quimico', '12 meses en almacenamiento', 'Ethanol 95%', NULL),
	(14352615, 1, 'Un liquido incoloro claro.', 'Quimico', '12 meses en almacenamiento', 'Ethanol 95%', NULL),
	(93049, 1, 'Liquido cristalino', 'Quimico', '36 meses en almacenamiento', 'Alcohol 100%', NULL),
	(80546, 2, 'Liquido aceitoso casi incoloro o amarilloso pastel', '24 meses en almacenamiento', 'Quimico', 'Aceite Parafina', NULL),
	(121335,2, 'Polvo blaco cristalino', '24 meses en almacenamiento', 'Quimico', 'Cloroformo', NULL),
	(106241,2, 'Liquido incoloro transparente', '24 meses en almacenamiento', 'Quimico', 'Keroseno', NULL),
	(28897214, 3, 'NA', 'NA', 'NA', 'NA', NULL),
	(18479577, 3 ,'Liquido transparente incoloro', 'Quimico', '2 años', '25% en alcohol a 75%', NULL),
	(5989548, 3, 'Liquido transparente incoloro', 'Quimico', 'NA', 'Aceites fijos', NULL),
	(504632, 4, 'Liquido transparente incoloro', 'Quimico', 'NA', 'Alcohol', NULL),
	(111273, 4, 'Liquido transparente incoloro', 'Quimico', 'NA', 'Alcohol', NULL),
	(542461, 4, 'Liquido cristalino incoloro o blanquecino', 'Quimico', '2 semanas', 'Glicol Dipropileno', NULL);
